
version: "3.9"
services:
  backend:
    build: ./backend
    ports: ["8000:8000"]
    volumes:
      - ./backend/app/data:/app/app/data
      - ./backend/app/db:/app/app/db
  frontend:
    build: ./frontend
    ports: ["5173:5173"]
    depends_on: [backend]
